# Prefer docker container with setuid/sudo
sudo: required

language: python

cache: pip

addons:
  apt:
    packages:
      - python-egenix-mxdatetime
      - python-mysqldb
      - python-psycopg2
      - python3-psycopg2
  postgresql: "9.4"

env:
  - TOXENV=py26-mysqldb
  - TOXENV=py27-mysqldb
  - TOXENV=py34-mysqlclient
  - TOXENV=py35-mysqlclient
  - TOXENV=py26-mysql-connector
  - TOXENV=py27-mysql-connector
  - TOXENV=py34-mysql-connector
  - TOXENV=py35-mysql-connector
  - TOXENV=py26-oursql
  - TOXENV=py27-oursql
  - TOXENV=py26-pymysql
  - TOXENV=py27-pymysql
  - TOXENV=py34-pymysql
  - TOXENV=py35-pymysql
  - TOXENV=py26-psycopg
  - TOXENV=py27-psycopg
  - TOXENV=py34-psycopg
  - TOXENV=py35-psycopg
  - TOXENV=py26-pygresql
  - TOXENV=py27-pygresql
  - TOXENV=py34-pygresql
  - TOXENV=py35-pygresql
  - TOXENV=py34-pypostgresql
  - TOXENV=py35-pypostgresql
  - TOXENV=py26-pg8000
  - TOXENV=py27-pg8000
  - TOXENV=py34-pg8000
  - TOXENV=py35-pg8000
  - TOXENV=py26-sqlite
  - TOXENV=py27-sqlite
  - TOXENV=py34-sqlite
  - TOXENV=py35-sqlite
  - TOXENV=py27-flake8
  - TOXENV=py34-flake8

install: pip install tox coveralls codecov

matrix:
  allow_failures:
    - env: TOXENV=py26-mysql-connector
    - env: TOXENV=py27-mysql-connector
    - env: TOXENV=py34-mysql-connector
    - env: TOXENV=py35-mysql-connector
    - env: TOXENV=py26-oursql
    - env: TOXENV=py27-oursql
    - env: TOXENV=py26-pymysql
    - env: TOXENV=py27-pymysql
    - env: TOXENV=py34-pymysql
    - env: TOXENV=py35-pymysql
    - env: TOXENV=py26-pygresql
    - env: TOXENV=py27-pygresql
    - env: TOXENV=py34-pygresql
    - env: TOXENV=py35-pygresql
    - env: TOXENV=py34-pypostgresql
    - env: TOXENV=py35-pypostgresql
    - env: TOXENV=py26-pg8000
    - env: TOXENV=py27-pg8000
    - env: TOXENV=py34-pg8000
    - env: TOXENV=py35-pg8000
  fast_finish: true

script: tox -e ${TOXENV}

after_success:
    - cd sqlobject
    - coveralls
    - codecov
